#!/bin/bash
# Slim WASM build: same as build_observer_wasm.sh but bakes the SLIM
# MPQs plus a handful of default maps into the .data blob via
# --preload-file. Users don't need to select or upload anything --
# just open the page and click connect.
#
# Prerequisites:
#   1. Slim MPQs generated by ./scripts/build_slim_mpq.sh. Look for
#      original_resources/{StarDat,BrooDat,Patch_rt}.slim.mpq. This
#      script errors out if any are missing.
#   2. emscripten SDK on PATH (emcc).
#
# Outputs:
#   wasm/dist/observer_wasm_slim.{html,js,wasm,data}
#   wasm/dist/index_slim.html         # user-facing shell
#
# The existing (upload-required) build at build_observer_wasm.sh is
# untouched; both variants coexist under wasm/dist/.

set -e

cd "$(dirname "$0")/.."   # repo root

# ---------- 1. Prereq check: slim MPQs must be generated ----------
MISSING=()
for name in StarDat BrooDat Patch_rt; do
    [ -f "original_resources/${name}.slim.mpq" ] || MISSING+=("${name}.slim.mpq")
done
if [ ${#MISSING[@]} -ne 0 ]; then
    echo "ERROR: missing slim MPQ file(s): ${MISSING[*]}" >&2
    echo "  Regenerate them first:" >&2
    echo "    cmake -S . -B build_srv -DOPENBW_BUILD_TOOLS=ON" >&2
    echo "    cmake --build build_srv --target slim_mpq" >&2
    echo "    ./scripts/build_slim_mpq.sh" >&2
    exit 1
fi

mkdir -p wasm/dist

SOURCES=(
    wasm/observer_wasm.cpp
    ui/sdl2.cpp
)

INCLUDES=(
    -I.
    -Iui
)

DEFINES=(
    -DOPENBW_NO_SDL_MIXER
    -DOPENBW_ENABLE_UI
)

FLAGS=(
    -std=c++14
    -O2
    -Wno-deprecated-declarations
)

# ---------- 2. Choose which files to preload into the VFS ----------
# Bake:
#   - the three slim MPQs (~18 MB total, from ./scripts/build_slim_mpq.sh)
#   - every top-level .scm / .scx map in original_resources/ (~4 MB
#     for the 44-map retail set)
#
# The .data blob emscripten produces is streamed once on the first
# visit and cached by the browser, so ~22 MB is a one-time cost
# (vs. the ~87 MB user-supplied full archives). Subfolders under
# original_resources/ (BroodWar/, campaign/, ladder/, oldladder/,
# scenario/ -- another ~29 MB) are intentionally NOT preloaded;
# users who want those can rebuild with a modified glob.
PRELOAD_MPQS=(
    --preload-file original_resources/StarDat.slim.mpq
    --preload-file original_resources/BrooDat.slim.mpq
    --preload-file original_resources/Patch_rt.slim.mpq
)

# Auto-enumerate every top-level .scm / .scx (case-insensitive) in
# original_resources/. Uses find with -maxdepth 1 so subfolders are
# skipped. The build fails loud if the directory has zero maps.
PRELOAD_MAPS=()
while IFS= read -r m; do
    PRELOAD_MAPS+=(--preload-file "$m")
done < <(find original_resources -maxdepth 1 -type f \
             \( -iname '*.scm' -o -iname '*.scx' \) | sort)

if [ ${#PRELOAD_MAPS[@]} -eq 0 ]; then
    echo "ERROR: no .scm/.scx maps found in original_resources/" >&2
    echo "  drop at least one melee map in there before building." >&2
    exit 1
fi
# Each map contributes two array elements (--preload-file, path), so
# the map count is half the array length.
echo "  baking in $((${#PRELOAD_MAPS[@]} / 2)) map file(s) from original_resources/"

EMSCRIPTEN_FLAGS=(
    -sUSE_SDL=2
    -sUSE_SDL_IMAGE=2
    -sSDL2_IMAGE_FORMATS=["png"]
    # emscripten 6.0.2+ disallows mixing --preload-file and
    # --embed-file in the same link (file_packager: "--preload and
    # --embed are mutually exclusive"). The regular build uses
    # --embed-file for the HUD console PNG; here we bring it in via
    # --preload-file to match the MPQ path. Same VFS-side effect,
    # just a slightly bigger .data blob (~18 KB more).
    --preload-file
    simsc_app/assets/tconsole_left.png@/simsc_assets/tconsole_left.png
    -sINITIAL_MEMORY=268435456
    -sEXPORTED_RUNTIME_METHODS=['ccall','cwrap','FS']
    -lwebsocket.js
    -sASYNCIFY=1
    -sASYNCIFY_STACK_SIZE=32768
    "${PRELOAD_MPQS[@]}"
    "${PRELOAD_MAPS[@]}"
)

echo "==> emcc compiling ${SOURCES[*]} (slim, self-contained)"
emcc "${SOURCES[@]}" \
    "${INCLUDES[@]}" \
    "${DEFINES[@]}" \
    "${FLAGS[@]}" \
    "${EMSCRIPTEN_FLAGS[@]}" \
    -o wasm/dist/observer_wasm_slim.html

# Copy the slim shell alongside the generated bundle. The regular
# index.html (from build_observer_wasm.sh) stays put -- we don't
# clobber it.
cp wasm/observer_shell_slim.html wasm/dist/index_slim.html

echo "==> Built wasm/dist/observer_wasm_slim.{html,js,wasm,data} + index_slim.html"
ls -la wasm/dist/observer_wasm_slim.* wasm/dist/index_slim.html
echo "==> To serve:"
echo "    cd wasm/dist && python3 -m http.server 8123"
echo "    open http://localhost:8123/index_slim.html"
